import { StyleSheet } from "react-native";

/* ────────────────────────────────────── */
/*  Estilos                               */
/* ────────────────────────────────────── */
export default StyleSheet.create({
  container: {
  flex: 1,
  backgroundColor: '#e1e1e1',
  alignItems: 'center',
  justifyContent: 'center',
  padding: 16,
},
  title: {
    width: '100%',
    fontSize: 22,
    fontWeight: 'bold',
    backgroundColor: '#b91c1c',
    color: '#ffffff',
    paddingHorizontal: 24,
    paddingVertical: 10,
    marginBottom: 12,
    borderRadius: 10,
    textAlign: 'center',
    alignSelf: 'center',
    elevation: 4,
    shadowColor: '#000',
  },
  panel: {
  backgroundColor: '#ffffff',
  borderRadius: 12,
  padding: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.05,
  shadowRadius: 4,
  elevation: 4,
},
  cameraView: {
    height: 220,
    alignSelf: 'center',
    backgroundColor: '#111827',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#444',
    aspectRatio: 4 / 3,
  },
  cameraText: {
    color: '#6b7280',
    fontStyle: 'italic',
    fontSize: 13,
    textAlign: 'center',
  },
  connectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 9999,
    marginRight: 6,
  },
  statusText: {
    fontSize: 13,
    color: '#1f2937',
  },
  joystick: {
    alignItems: 'center',
    marginTop: 4,
  },
  joystickRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 6,
  },
  arrowButton: {
    width: 80,
    height: 80,
    backgroundColor: '#b91c1c',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    elevation: 2,
  },
  arrowText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  stopButton: {
    width: 80,
    height: 80,
    backgroundColor: '#4b5563',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
    elevation: 3,
  },
  stopText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  modalContent: {
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: 360,
    borderRadius: 12,
    padding: 24,
    borderColor: '#e5e7eb',
    borderWidth: 1,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
    color: '#111827',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 8,
    borderRadius: 6,
    marginTop: 10,
    fontSize: 14,
    backgroundColor: '#f9fafb',
    color: '#111827',
  },
  infoButton: {
    backgroundColor: '#b91c1c',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 9999,
    marginTop: 12,
    alignSelf: 'center',
  },
  infoButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalCloseText: {
    color: '#b91c1c',
    fontWeight: 'bold',
    fontSize: 14,
  },
  modalButtonContainer: {
  marginTop: 20,
  gap: 12,
},

botonPrimario: {
  backgroundColor: '#b91c1c',
  paddingVertical: 12,
  borderRadius: 9999,
  alignItems: 'center',
  marginTop: 15,
},
botonPrimarioTexto: {
  color: '#ffffff',
  fontWeight: 'bold',
  fontSize: 14,
},

botonSecundario: {
  backgroundColor: '#6b7280',
  paddingVertical: 12,
  borderRadius: 9999,
  alignItems: 'center',
},
botonSecundarioTexto: {
  color: '#ffffff',
  fontWeight: 'bold',
  fontSize: 14,
},

botonTerciario: {
  paddingVertical: 10,
  alignItems: 'center',
},
botonTerciarioTexto: {
  color: '#b91c1c',
  fontWeight: 'bold',
  fontSize: 14,
},
});